### ISSUE TITLE
Colloboration

### ISSUE THREAD

**Issue by davidhopkins** [TarasMazepa/stax#168]
Apologies but I am new to the world of stacking. How can multiple people commit changes to a PR that is part of a stack? As i understand it all changes must be pushed with stacking tool but there is no way that I can see to "download" the stack -- meaning the other person could never push a commit to the PR -- or if they did just push a regular commit, I assume that might corrupt the stack?

**Comment by TarasMazepa** [comment]
Hi @davidhopkins ! Thanks for checking this tool out! Here is the list of things you highlighted.

1. How can multiple people commit changes to a PR that is part of a stack?

Right now stax can only help you with:
 * `stax commit` - creating branch, commit and pushing it to the remote 
 * `stax amend` - amending to the current commit and force pushing it to the remote
 * `stax log` - showing you all of your local branches and how the relate to each other
 * `stax delete-gone-branches` - deletes your local gone branches
 * `stax pull` - checkout <remote>/HEAD pull, delete gone branches, checkout back your branch
 * `stax rebase` - rebasing tree of branches and force pushing them to the remote

`stax amend`, and `stax rebase` are doing a force push, which might be tricky for collaboration. 

`stax log`, `stax delete-gone-branches`, `stax pull` producing changes only locally

`stax commit` will create new branch when you use if which would be considered from stax and git point of view as new PR in the stack.

so you are left with functionality that `git` provides you. 

Stax by itself was designed to compliment your workflow rather then dictate how to use it, that is why stax is always printing list of commands it performs.


2. As I understand it, all changes must be pushed with the stacking tool?

stax doesn't require you to use stax all the time, you can use it for some of your workflow.

from stax point of view branch is an item in a stack, you can do whatever you want with branches and stax should pick it up properly. 

But you would be left to yourself to manage that changes. 

3. There is no way that I can see to "download" the stack

stack from stax point of view is just a set of branches that might form some sort of a tree, here is the output of the `stax log` command for one of mine test repositories:
```
o       AABAEEBGHC_7_1_8
o       AABAEEBGHC_7_1_6
| o     AABAEEBGHC_7_1_5
o-┘     AABAEEBGHC_7_1_4
| o     AABAEEBGHC_7_1_10
| o     AABAEEBGHC_7_1_2
| | o   AABAEEBGHC_7_1_9
| | x   AABAEEBGHC_7_1_7
| | | o AABAEEBGHC_7_1_3
| | o-┘ AABAEEBGHC_7_1_1
o-┘-┘   AABAEEBGHC_7_1_0
```

note: `x` means you are currently at that node (branch or other git ref)

`stax log` sees all the local branches and tries to build graph representation of them.

so if you want to download a stack you can use `git checkout` to have local copies of branches that interest you.

This give me an idea for tow changes in stax that will make this experience easier:
    * Allowing log to show remote branches too (so you can see which stacks you might be interested in)
    * download command that will checkout locally branches of stack you want

4. Meaning the other person could never push a commit to the PR

Stax sees branch as a single item of the stack, if you will use git to add new commit to the existing branch and push it to remote you should be good. If that commit was for a stacked PR in the middle of the stack, you can use `stax rebase` to rebase child branches and have them updated on the remote.

5. If they did just push a regular commit, I assume that might corrupt the stack?

It depends on what you define as corrupt. if you push new commit, other people need to pull that branch from remote, if they would not do that, and will come up with their own changes and push to remote once again, then yes you can endup in corrupt state.


### General thoughts about stacking

For me stacking a way to reduce need to come back to PRs once I have pushed them - most of them should be merged without changes. If reviewers require you to make changes, I would rather create new PR on top of the stack to address the feedback. Let alone collaboration.

If I were in your team where you end up doing collaboration in stacked PRs, I would focus first on the reason why collaboration is needed and why can't people just depend on each others stacked PRs.

This was a long one. Let me know if I missed something.

BTW, if you want to have live conversation about the topic, feel free to hop on [my discord channel](https://discord.com/invite/4Xuk7bKgGC)

**Comment by davidhopkins** [comment]
Thanks for the feedback! Now that I have had a play with the stax, I understand how it works much better. When I asked my question, it was after I was playing around with [stack-pr](https://github.com/modularml/stack-pr) (I found your project from the GitHub issue you opened on that project) `stack-pr` adds metadata to the PRs such that you are unable to push regular commits because it breaks the workflow. I assumed your tool worked in a similar way but now I realise your approach is much simpler (which i prefer!)

> For me stacking a way to reduce need to come back to PRs once I have pushed them - most of them should be merged without changes. 

I agree that smaller PRs should result in simpler reviews but surely the whole purpose of a PR is to have a discussion about the code? Those discussions _should_ sometimes result in updates being requested/made otherwise the PR stops being a discussion and instead become more of a "box to be ticked" -- which I understand is one of the things stacks were designed to solve?

**Comment by TarasMazepa** [comment]
It is nice to hear back from you!

Regarding actionable feedback on PRs, I see two ways to approach them:
1. Instead of modifying the original PR, you would just go and create a new PR on top of the stack

2. Update PR and rebase/update PRs that depend on it.

1) Move to the appropriate branch using a combination of `stax log` (shows a graph of branches), `stax move` (allows to move through the graph using directions), or `git checkout`, `git log`
2) Make a change, push a new change using either `stax amend` (amends and force pushes) or `git commit`, `git push` or `git commit --amend`, `git push`
3) Rebase any child branches on top of changed PR using either `stax rebase` (rebases trees of branches and force pushes them to the remote), `stax log` or `git rebase`, `git log`


> I agree that smaller PRs should result in simpler reviews but surely the whole purpose of a PR is to have a discussion about the code? Those discussions should sometimes result in updates being requested/made otherwise the PR stops being a discussion and instead become more of a "box to be ticked" -- which I understand is one of the things stacks were designed to solve?

Yes! I'm sorry for confusing you 😅 


Regarding the general approach of stacking, you can check out these two of my videos on YouTube (they are low-effort):

[Why stack pull request?](https://youtu.be/gJu0oseqaqs)

[Checking out stacking workflow](https://www.youtube.com/watch?v=zoqbYxW3saY)

**Comment by davidhopkins** [comment]
Thank you for the tips, will check them out!

**Comment by TarasMazepa** [comment]
@davidhopkins BTW, with new stax version 0.9.2 there is new command `stax get` which will "download" stack of PR you just need to provide bottom most branch name as a argument. Also `stax log` got new flag `-a` which will show you all remote branches, so you can take a look which stacks you want to download with `stax get`.
