### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by Mike-Jagger** [TarasMazepa/stax#42]
I recently came across this issue when trying to run stax commands.

![image](https://github.com/TarasMazepa/stax/assets/88729231/edea0604-79cf-40b7-a639-5340eb60b7c8)

There seems to be an issue with either the version of dart I am using or the `bin/stax.dill` kernel file. Any fix for this would be greatly appreciated

**Comment by TarasMazepa** [comment]
I think `*.dill` files are not portable, and if you compile it with one version of Dart and run on a different version, execution may fail. I will provide a fix shortly.

**Comment by TarasMazepa** [comment]
@Mike-Jagger can you check now? it should be working.

**Comment by Mike-Jagger** [comment]
It works @TarasMazepa !

Pulled latest changes:
![image](https://github.com/TarasMazepa/stax/assets/88729231/bbfaa99b-2b33-4965-9780-bda6b10442bd)

Ran `stax help` command on command line
![image](https://github.com/TarasMazepa/stax/assets/88729231/da5100aa-2c08-4573-ba68-da5572dd92b6)

However, in git bash, I get this error:
![image](https://github.com/TarasMazepa/stax/assets/88729231/194e8d0c-b9d9-4559-a0a4-3e29a591dd3f)

Seems to be related to [this kernel file](https://github.com/TarasMazepa/stax/blob/main/bin/macos-x64/stax)

**Comment by Mike-Jagger** [comment]
Never mind the second issue mentioned previously.

Pulled the latest changes
![image](https://github.com/TarasMazepa/stax/assets/88729231/7a3416bf-7ec2-426c-906b-2d2df652dce4)

Now works fine
![image](https://github.com/TarasMazepa/stax/assets/88729231/c603ca6a-7caa-49f5-a037-36e010babb0a)

**Comment by TarasMazepa** [comment]
@Mike-Jagger , yeah, I tested it with MinGW and it wasn't working so I did an update :)
